version: "3.9"
services:
  smtp:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    #   - 1025:1025

  postfix:
    build: .
    working_dir: /app
    volumes:
      - .:/app

  php:
    build: docker/php
    working_dir: /app
    volumes:
      - .:/app
